name: GEE
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --user --no-cache-dir Cython
                  pip install --user -r requirements.txt
                  pip install --user .
            - name: PROCESS
              run:  |
                   python functions/credentials.py
                   python functions/server.py
              env:
                  EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}


            - uses: stefanzweifel/git-auto-commit-action@v2

              with:
                commit_message: "Actualizacion"
                branch: main
                # Optional glob pattern of files which should be added to the commit
                #file_pattern: /

                # Optional local file path to the repository
                repository: .

                # Optional commit user and author settings
                commit_user_name: Actions Bot
                # commit_user_email: gholley42@gmail.com
                # commit_author: DataIntelligence BOT <gholley42@gmail.com>

                commit_user_email: hectorflores329@gmail.com
                commit_author: DataIntelligence BOT <hectorflores329@gmail.com>

                push_options: '--force'
            
